name: VoltramDrops
main: main.VoltramDrops
depend: [WorldEdit, HolographicDisplays]
version: 1.0
api-version: 1.13
author: Griillz
commands:
  vd:
    description: Main command VoltramDrops
    usage: /vd <create> <region_name>